### ISSUE TITLE
Skill Strength Viewer doesn't work on non-English base languages

### ISSUE THREAD

**Issue by graciecat** [halfdan/duolingo-skill-strength#1]
Thanks for updating your script to work on the new Duolingo website.

However, I notice that the script works only when the base language is English. When the base language is something other than English, it does not work. 

For example, when the user is learning Italian from English, the Skill Strength window appears:
![italian from english](https://cloud.githubusercontent.com/assets/18286141/25798550/97e68918-33af-11e7-9907-09df4587c6ad.png)

But when the user is studying Italian from Spanish, the Skill Strength window does not appear:
![italiano desde espanol](https://cloud.githubusercontent.com/assets/18286141/25798542/92720782-33af-11e7-8627-43b20f418873.png)

**Comment by AbsolutelyFreeWeb** [comment]
this is now fixed
