### ISSUE TITLE
Some skills not strengthening

### ISSUE THREAD

**Issue by graciecat** [halfdan/duolingo-skill-strength#2]
Regarding your updated userscript for the new site, have you seen [this discussion thread](https://www.duolingo.com/comment/22496670)? Some of the skills do not appear to strengthen in the Skill Strength chart, no matter how much practice you give them.

(I am not talkng about the skills' appearance in the tree, but the numbers in the chart your script provides).

Some people think it is the website, but maybe it is the script. Even if it is the website, maybe it can be accounted for in the script?

Right now, I am experiencing the same problem. I have installed the script, but it is not so useful to me anymore when several skills won't strengthen (the percentages won't change). It's not every skill in every language, but certain skills, particularly People in Spanish (from English) just don't change much (if at all). I am stuck in the low-20s in People. 

I hope this is something fixable!

**Comment by AbsolutelyFreeWeb** [comment]
it is a duolingo bug not a script bug. If you go to the words tab in duolingo, the words there are not updating either. Nothing we can do.
