### ISSUE TITLE
Skill strength does not work in firefox (54.0.1 32bit)

### ISSUE THREAD

**Issue by lok76** [halfdan/duolingo-skill-strength#4]
BTW: Thanks a lot for this script, I used it a lot!

I just installed the new version 0.2 (the old one 0.1 worked only till ~May), but it seems not to work. I just started a 'naked' firefox without the typical addons (just greasmonkey) and only skill strength 0.2. 

See screenshot: 
![error skill strength](https://user-images.githubusercontent.com/30112983/28112884-dc928a0c-66fa-11e7-80fd-fdd9f33b3943.jpg)

**Comment by AbsolutelyFreeWeb** [comment]
oh it wasn't working in firefox either. Alright, maybe my pull request for chrome fixes it for firefox too. Could you test it please ?

**Comment by lok76** [comment]
Did a quick test with 63.0.1, 64bit, Windows7: Still not working. Checked with chrome too. Works nicely if i start duolingo or click on start, but doesn't after returning from a practice session (Chrome: 70.0.3538.77 (Offizieller Build) (64-Bit))
For me ok enough to use chrome and refresh page: Big thanks again for the script!

**Comment by AbsolutelyFreeWeb** [comment]
@lok76 strange. I’m on same chrome version 70.0.3538.77 and script v 0.2.1 updates values for me after practice without need of refresh.

**Comment by lok76** [comment]
@AbsolutelyFreeWeb I quickly installed everything on my workplace machine (Win10!) and it works perfectly with the same chrome version. Retested on Win7 - still no skill strength after return from practice, only if you refresh page. Again, good enough for me.

**Comment by lok76** [comment]
Just found this still open, but it had been fixed (at least in Chrome)
